### ISSUE TITLE
重命名插件前置DayCount-NBT会导致joinMOTDnext无法运行

### ISSUE THREAD

**Issue by Pau1am** [JOZA-ORANGE/MCDR-joinMOTDnext#2]
发现一个问题，该插件侦测前置DayCount NBT的方式貌似是透过读取插件的文件名？当我对DayCount NBT插件重命名后（将插件名由 “DayCountNBT-v2.2.1.mcdr”改为 "[开服时间]DayCountNBT-v2.2.1.mcdr"，方便辨别插件功能），重启服务器，出现以下报错:

`[MCDR] [23:44:28] [TaskExecutor/ERROR]: Fail to load the entry point of join_motd_next@0.1.0
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 66, in _on_ready
    self._load_entry_instance()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mcdreforged\plugin\type\multi_file_plugin.py", line 34, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "plugins\[入服提醒joinMOTDnext-v0.1.0.mcdr\join_motd_next\__init__.py", line 5, in <module>
    from daycount_nbt import getday
ModuleNotFoundError: No module named 'daycount_nbt'`

使得该插件无法在服务器运作。

**Comment by JOZA-ORANGE** [comment]
我没有复现出你的这个问题
如果没有修改名字，会出现这个问题吗

**Comment by Pau1am** [comment]
> 我没有复现出你的这个问题 如果没有修改名字，会出现这个问题吗

如果名字保持不变，为DayCountNBT-v2.2.1.mcdr则没有问题

**Comment by Pau1am** [comment]
补充:
1.MCDR版本:2.9.1
2.Join MOTD Next版本:0.1.0
3.Day Count NBT版本: 2.2.1

复现方式:
1.安装Day Count NBT和Join MOTD next插件
2.修改plugins文件中Day Count NBT插件的文件名称，如下图所示:
![image](https://github.com/JOZA-ORANGE/MCDR-joinMOTDnext/assets/41251296/6741ceae-f68f-4c86-8c0e-216859296145)
3.运行服务器，出现以下报错:
![image](https://github.com/JOZA-ORANGE/MCDR-joinMOTDnext/assets/41251296/358a98d1-d31c-4735-aa8b-c835e8594573)

图中可见插件Day Count NBT已被加载，而Join MOTD next插件则发出No module named 'daycount_nbt'的报错，应该是插件侦测前置的方式问题。

**Comment by JOZA-ORANGE** [comment]
已更新新版本，应该没有问题了

**Comment by Pau1am** [comment]
经过测试，问题已修复，非常感谢。
