### ISSUE TITLE
插件无法加载

### ISSUE THREAD

**Issue by swe3per** [JOZA-ORANGE/MCDR-joinMOTDnext#3]
已安装daycount_nbt，并pip安装nbtlib，服务器内可正常显示游戏天数。
但MCDR启动提示无法调用插件：
```
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 info@0.2.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 timed_quick_backup_multi@1.3.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 dict_command_registration@1.1.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 where_is@2.0.2+build.6 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 beep@1.1.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 start_stop_helper_r@0.1.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.9.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 here@1.2.2 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 bot@1.0.6 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 location_marker@1.3.2 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 stats_helper@7.5.1 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 advanced_calculator@0.3.1 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 join_motd_next@0.1.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 more_command_nodes@1.1.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 gamemode@1.0.1 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 seed@1.2.0 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 minecraft_data_api@1.4.1 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO]: 插件 daycount_nbt@2.2.1 已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [where_is]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/ERROR]: Fail to load the entry point of join_motd_next@0.1.0
Traceback (most recent call last):
  File "/home/sweeper/.local/lib/python3.8/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 66, in _on_ready
    self._load_entry_instance()
  File "/home/sweeper/.local/lib/python3.8/site-packages/mcdreforged/plugin/type/regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
  File "/home/sweeper/.local/lib/python3.8/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 34, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins/joinMOTDnext-v0.1.0.mcdr/join_motd_next/__init__.py", line 5, in <module>
    from daycount_nbt import getday
ModuleNotFoundError: No module named 'daycount_nbt'
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [info]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [quick_backup_multi]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [timed_quick_backup_multi]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [start_stop_helper_r]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [here]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [bot]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [location_marker]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [stats_helper]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [stats_helper]: UUID list size: 24
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [gamemode]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [seed]: 配置文件已加载
[MCDR] [2023-08-01 23:27:47] [TaskExecutor/INFO] [daycount_nbt]: 配置文件已加载
```

**Comment by JOZA-ORANGE** [comment]
请尝试使用最新版的插件，即[join_motd_next@0.2.0](https://github.com/JOZA-ORANGE/MCDR-joinMOTDnext/releases/tag/0.2.x)

**Comment by swe3per** [comment]
```
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO]: 插件 advanced_calculator@0.3.1 已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO]: 插件 more_command_nodes@1.1.0 已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO]: 插件 gamemode@1.0.1 已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO]: 插件 join_motd_next@0.2.0 已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO]: 插件 seed@1.2.0 已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO]: 插件 minecraft_data_api@1.4.1 已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO]: 插件 daycount_nbt@2.2.1 已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [where_is]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/ERROR]: Fail to load the entry point of join_motd_next@0.2.0
Traceback (most recent call last):
  File "/home/sweeper/.local/lib/python3.8/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 66, in _on_ready
    self._load_entry_instance()
  File "/home/sweeper/.local/lib/python3.8/site-packages/mcdreforged/plugin/type/regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
  File "/home/sweeper/.local/lib/python3.8/site-packages/mcdreforged/plugin/type/multi_file_plugin.py", line 34, in _import_entrypoint_module
    mod = importlib.import_module(self.get_metadata().entrypoint)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "plugins/joinMOTDnext-v0.2.0.mcdr/join_motd_next/__init__.py", line 30, in <module>
    def msg_to_rtextlist(row: list[dict], player: str) -> RTextList:
TypeError: 'type' object is not subscriptable
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [info]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [quick_backup_multi]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [timed_quick_backup_multi]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [start_stop_helper_r]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [here]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [bot]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [location_marker]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [stats_helper]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [stats_helper]: UUID list size: 25
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [gamemode]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [daycount_nbt]: 配置文件已加载
[MCDR] [2023-08-02 17:05:34] [TaskExecutor/INFO] [seed]: 配置文件已加载
```

emmmm。。。难道我环境有问题？

**Comment by JOZA-ORANGE** [comment]
请问你的python版本和mcdr版本?

---
尝试更新到 [v0.2.1](https://github.com/JOZA-ORANGE/MCDR-joinMOTDnext/releases/tag/0.2.1)，看看这个问题有没有修复

**Comment by swe3per** [comment]
Python 3.8.10
MCDR 2.10.2
经过测试0.2.1加载不报错并且游戏中表现正常 感谢！！
